apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: skupper-operator
  namespace: operators
spec:
  sourceType: grpc
  image: quay.io/fgiorgetti/skupper-operator-index:v0.0.1
